### ISSUE TITLE
'MapboxSceneKit' not yet in cocoapod registry 

### ISSUE THREAD

**Issue by camdeardorff** [mapbox/mapbox-scenekit#3]
When trying to install the pod I was receiving this error.

**[!] Unable to find a specification for `MapboxSceneKit`**

I went to search the cocoapod registry but was not able to find it.

**Comment by dh06IRL** [comment]
Should be a quick work around:
`pod 'MapboxSceneKit', :git => 'https://github.com/mapbox/mapbox-scenekit.git'`

**Comment by camdeardorff** [comment]
Yes that does work, but when I tried it last the pod was empty within the workspace. I assumed that would be fixed once the pod was generated. 

If you try that and have different results let me know @dhodge229.

**Comment by 1ec5** [comment]
The podfile in this repository appears to have been copy-pasta’d from the navigation SDK:

https://github.com/mapbox/mapbox-scenekit/blob/cb3dad5687a83ab9d468df605079ee9ecfe6fee5/MapboxSceneKit.podspec#L35

The podfile needs to be rewritten for the SceneKit SDK.

/ref #6
/cc @avi-c @bsudekum
