### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by natalia-osa** [mapbox/mapbox-scenekit#35]
The way of doing the documentation is unknown to Xcode. If you click `⌘` + `⌥` + `/` the default way of adding documentation will be used (and all of the arguments names will be filled automatically, leaving you doing the important stuff).

It is undestandable by Xcode and instead of such documentation:
<img width="1131" alt="unknown arguments" src="https://user-images.githubusercontent.com/1477880/44725581-eb76fd80-aad5-11e8-99d2-6c2865304e54.png">

you'll get such output:
<img width="1106" alt="documented arguments" src="https://user-images.githubusercontent.com/1477880/44725588-efa31b00-aad5-11e8-9f35-e0af3772975b.png">

As you can notice, in both cases first two arguments are described, but in the first case the description of the argument goes to the method description and leaves the argument without documentation, in second case everything is in the proper place.

**Comment by jim-martin** [comment]
It looks like this fix was rolled into a bigger PR.
