### ISSUE TITLE
Spikey terrain data.

### ISSUE THREAD

**Issue by natalia-osa** [mapbox/mapbox-scenekit#44]
The terrain is spikey in certain places. We can observe it especially nearby Snowdon in the UK. As a result, we receive the following output:

![spikey3dbug](https://user-images.githubusercontent.com/1477880/45173260-efa6c780-b207-11e8-91af-aa142465f6be.png)

**Comment by avi-c** [comment]
Here is an image from the sample project showing the issue:

![image](https://user-images.githubusercontent.com/10037825/45173322-aed59100-b1bc-11e8-86e9-f3d3f62ad6bb.png)

**Comment by natalia-osa** [comment]
Ow, the terrain on which it happens, as an example, is:
53.063137900000001
53.0745991
-4.0644666000000003
-4.0349393999999998
