### ISSUE TITLE
Unable to show PolyLineNode on TerrainNode

### ISSUE THREAD

**Issue by camdeardorff** [mapbox/mapbox-scenekit#52]
using the `addPolyLine` function I am unable to get a line to appear although I can see the child count increase. I am getting an error in the console related to a missing library.

Couldn't locate default library for bundle: NSBundle </var/containers/Bundle/Application/E7B20083-1807-4AC4-966C-2153FAA81E14/appname.app/Frameworks/MapboxSceneKit.framework> (loaded)
Error Domain=MTLLibraryErrorDomain Code=6 "no default library was found" UserInfo={NSLocalizedDescription=no default library was found}
1
2018-09-18 22:07:24.982061-0600 appname[599:59243] [SceneKit] Error: FATAL ERROR : can't load library without a path

**Comment by rockarts** [comment]
@camdeardorff Are you running it on a phone? I see the polyline in the simulator but not on a device.

**Comment by camdeardorff** [comment]
This is on device, I have not tried on a simulator yet. Good to know though, that helps!

**Comment by jim-martin** [comment]
@camdeardorff & @rockarts, I'm able to see this issue when using cocoapods. To confirm we're seeing the same issue, are you using pods? 

I'm looking into a fix now, but in the meantime, the Carthage install instructions should work as expected.

**Comment by camdeardorff** [comment]
Yes I am, and thank you @jim-martin

**Comment by rockarts** [comment]
@jim-martin That fixed it. Thanks!

**Comment by camdeardorff** [comment]
Same, thanks again @jim-martin
