### ISSUE TITLE
Attribution and telemetry

### ISSUE THREAD

**Issue by luca-dall** [mapbox/mapbox-scenekit#72]
Hallo! In our app we are implementing an AR Scene using the satellite layer and I have some questions:

- I haven't found any information about the attribution in SceneKit. We will place the following text with links on the bottom of the View: _© Mapbox © OpenStreetMap © DigitalGlobe_ is this enough?

- Is the telemetry active within Mapbox SceneKit? Do I have to add a paragraph about it inside our Terms of Conditions?

- How are the Map Views counted with SceneKit? each tile? (overlay and height map)?

**Comment by avi-c** [comment]
Hi @luca-dall - I'm getting the official answer to your questions now and will reply when I sort it out.

**Comment by jordy-isaac** [comment]
@luca-dall Thanks for reaching out! Let's see what I can do to answer your questions.

>I haven't found any information about the attribution in SceneKit. We will place the following text with links on the bottom of the View: © Mapbox © OpenStreetMap © DigitalGlobe is this enough?

This would be proper attribution. For our Maps SDK for iOS we include an attribution UI, and you could refer to that as an example if you would like to implement something similar. You could aslo do a text version like you mentioned and as outlined in the documentation [here](https://www.mapbox.com/help/how-attribution-works/#mapbox-maps-sdk-for-ios).

>Is the telemetry active within Mapbox SceneKit? Do I have to add a paragraph about it inside our Terms of Conditions?

Telemetry is active in the SceneKit SDK. We do require that you provide users with a way to [opt out](https://www.mapbox.com/help/how-mobile-apps-work/#telemetry).

>How are the Map Views counted with SceneKit? each tile? (overlay and height map)?

For info on map views we have a guide you can check out [here](https://www.mapbox.com/help/define-map-view/#mapbox-static-api-1-request). The SceneKit uses static api calls which are one map view per request. However, our mobile SDKs billing is based on monthly active users. On our pay as you go plan, you can have up to 50K MAU's. For more info, please check out the [pricing page](https://www.mapbox.com/pricing/). If you have a paid app or keep your maps behind a login, you'll need a commercial plan. 

We'd love to hear more about what your building! Please let us know if we can do anything else to help. If you have any other questions about your plan and billing please email us at help@mapbox.com or get in touch with our [sales team](https://www.mapbox.com/contact/sales/) for the fastest help.

**Comment by luca-dall** [comment]
Thanks for the detailed answer!

We will probably create a UI for the attribution and telemetry opt-out. Or is the standard UI already shipped with the SDK?

We are building an application that helps to orchestrate mobility and we want to display journeys also on a AR map.
