### ISSUE TITLE
Rewrite Cartfile

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-scenekit#8]
The Mapbox Maps SDK is only used in the example application, so this line should go in Cartfile.private so that downstream users of this library don’t necessarily depend on the map SDK:

https://github.com/mapbox/mapbox-scenekit/blob/cb3dad5687a83ab9d468df605079ee9ecfe6fee5/Cartfile#L2

Are there any other dependencies that should be mentioned in the Cartfile?

/ref #3 #5
/cc @avi-c

**Comment by avi-c** [comment]
There aren't any other dependencies for now.
Could you create a PR for these changes?
