### ISSUE TITLE
MapboxImageAPI - build error

### ISSUE THREAD

**Issue by junsolOh** [mapbox/mapbox-scenekit#90]
<img width="978" alt="스크린샷 2020-09-15 오후 1 46 31" src="https://user-images.githubusercontent.com/62420064/93166762-26e6d200-f75a-11ea-99aa-5141adef9e54.png">

  pod 'MapboxSceneKit', :git => 'https://github.com/mapbox/mapbox-scenekit.git'
  pod 'MapboxMobileEvents'

I modified the podfile, pod repo update, and pod install.

Then I get the following error.
1. Value of type 'MMEEventsManager' has no member 'isMetricsEnabledInSimulator'
2. Value of type 'MMEEventsManager' has no member 'isMetricsEnabledForInUsePermissions'

What is the reason?

**Comment by pranavsekhar** [comment]
Any chance you were able to solve this? I'm running into the same issue right now
